Resources:
  # RDS Resources

  MasterUserDB:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: ${self:service}${self:provider.stage}MasterUserDB
      DBClusterIdentifier: ${self:service}-${self:provider.stage}-masterusercluster
      EnableHttpEndpoint: True
      Engine: aurora-postgresql
      EngineVersion: 15.4
      EngineMode: provisioned
      MasterUsername: postgres
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${DatabaseKeys}::password}}"
      Port: 5432
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 2

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-postgresql
      EngineVersion: 15.4
      DBClusterIdentifier: !Ref MasterUserDB
      DBInstanceClass: db.serverless
      PubliclyAccessible: true
    DependsOn:
      - MasterUserDB

Outputs:
  DatabaseName:
    Value: ${self:resources.1.Resources.MasterUserDB.Properties.DatabaseName}
    Export:
      Name: ${self:service}-${self:provider.stage}-DatabaseName

  DbClusterARN:
    Value: arn:aws:rds:${self:provider.region}:${aws:accountId}:cluster:${self:resources.1.Resources.MasterUserDB.Properties.DBClusterIdentifier}
    Export:
      Name: ${self:service}-${self:provider.stage}-DbClusterARN
