Resources:
  CoralogixKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}/${self:provider.stage}/CoralogixKey
      SecretString: '{
        "CoralogixKey": "ad0e94ce-b59d-8e11-e3f7-93f825222407"
        }'

  ApplicationKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}/${self:provider.stage}/ApplicationKey
      SecretString: '{
        "AppKey": "EnterApplicationKey"
        }'

  AppKeyRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      RotationLambdaARN:
        "Fn::GetAtt": [RotateSecretLambdaFunction, Arn]
      RotationRules:
        AutomaticallyAfterDays: 30
      SecretId:
        Ref: ApplicationKey

  DatabaseKeys:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}/${self:provider.stage}/DatabaseKeys
      SecretString:
        Fn::Sub:
          - '{"dbInstanceIdentifier": "${Value1}","engine": "${Value2}","host": "${Value3}","port": "${Value4}","resourceId": "${Value5}","username": "${Value6}","password":"${Value7}"}'
          - Value1: ${self:resources.1.Resources.MasterUserDB.Properties.DBClusterIdentifier}
            Value2: ${self:resources.1.Resources.MasterUserDB.Properties.Engine}
            Value3:
              "Fn::GetAtt": [MasterUserDB, Endpoint.Address]
            Value4: ${self:resources.1.Resources.MasterUserDB.Properties.Port}
            Value5:
              Ref: MasterUserDB
            Value6: ${self:resources.1.Resources.MasterUserDB.Properties.MasterUsername}
            Value7: ${self:resources.1.Resources.MasterUserDB.Properties.MasterUserPassword}

Outputs:
  DbCredentialsSecretsStoreARN:
    Value:
      Ref: DatabaseKeys
    Export:
      Name: ${self:service}-${self:provider.stage}-DbCredentialsSecretsStoreARN

  CoralogixSecret:
    Value:
      Ref: CoralogixKey
    Export:
      Name: ${self:service}-${self:provider.stage}-CoralogixSecret

  AppKeySecretARN:
    Value:
      Ref: ApplicationKey
    Export:
      Name: ${self:service}-${self:provider.stage}-AppKeySecretARN